### PR TITLE
Bond Reporting Postgrest Config

### PR DESCRIPTION
**Pull request by Charlie-Henry**
Testing for adding Bond Reporting tables to Postgrest

### CODE REVIEW

**Review by johnclary — CHANGES_REQUESTED** [review]
@Charlie-Henry this looks great! our prod server is currently running this branch w/o issue. 

One small thing: would you please update [this section](https://github.com/cityofaustin/atd-postgrest#services) of README with the bond reporting deets?

**Comment by johnclary** [comment]
@Charlie-Henry one more thing, would you add your new postgrest service and road conditions to the `depends_on` block?
https://github.com/cityofaustin/atd-postgrest/blob/85396da5b8d9766f59b0b59461af84921870199d/docker-compose.yaml#L6

**Comment by Charlie-Henry** [comment]
Should be addressed @johnclary thank you for your help on getting this set up!

**Comment by johnclary** [comment]
thanks @Charlie-Henry! i'm merging this and moving our production server back to this branch.

**Comment by johnclary** [comment]
cc @chiaberry

**Pull request merged**
